server {
    listen 80;

    # ========================================================
    # 🌟 SOLUSI ERROR 413: Izinkan Upload File sampai 50 MB
    # ========================================================
    client_max_body_size 50M;

    # 1. Pintu masuk ke Auth Service
    location /api/auth/ {
        proxy_pass http://auth-service:8000/api/;
        proxy_set_header Host $http_host; # <--- UBAH DI SINI
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Pintu masuk ke Info Service (Berita dll)
    location /api/info/ {
        proxy_pass http://info-service:8001/api/;
        proxy_set_header Host $http_host; # <--- UBAH DI SINI
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Pintu masuk ke Statistic Service
    location /api/statistic/ {
        proxy_pass http://statistic-service:8002/api/;
        proxy_set_header Host $http_host; # <--- UBAH DI SINI
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Pintu masuk ke Content Service
    location /api/content/ {
        proxy_pass http://content-service:8003/api/;
        proxy_set_header Host $http_host; # <--- UBAH DI SINI
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 5. Pintu masuk khusus untuk mengambil Gambar/File di Info Service
    location /storage/ {
        proxy_pass http://info-service:8001/storage/;
        proxy_set_header Host $http_host; # <--- UBAH DI SINI
        proxy_set_header X-Real-IP $remote_addr;
    }
}